<?php

namespace BooksSearchBundle\Repository;

/**
 * SearchInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
