<?php

namespace BooksSearchBundle\Repository;

/**
 * VolumeInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolumeInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
