imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
# only for unit testing
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%_test'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
#doctrine:
#    dbal:
#        default_connection: default
#
#        connections:
#            default:
#                driver:  pdo_sqlite
#                user:    test
#                path:    %kernel.root_dir%/sqlite.db.cache
#                memory: true
#                charset: utf8
#    orm:
#        entity_managers:
#            default:
#                metadata_cache_driver: apc
#                query_cache_driver:    apc
#                result_cache_driver:   apc