BooksSearchBundle\Entity\Author:
    type: entity
    table: null
    repositoryClass: BooksSearchBundle\Repository\AuthorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    manyToMany:
        itemRecords:
            targetEntity: VolumeInfo
            mappedBy: authors     
    lifecycleCallbacks: {  }
