BooksSearchBundle\Entity\Book:
    type: entity
    table: null
    repositoryClass: BooksSearchBundle\Repository\BookRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        gid: 
            type: string
            length: '32'
            unique: true
        etag: 
            type: string
            length: '32'
            unique: true
        selfLink: 
            type: string
            length: '255'
            column: self_link
            unique: true
    oneToOne:
        volumeInfo:
            targetEntity: VolumeInfo
            inversedBy: book
            cascade: ["all", "merge", "persist", "refresh", "remove"]
            joinColumn:
              name: volume_id
              referencedColumnName: id
              onDelete: CASCADE
        searchInfo:
            targetEntity: SearchInfo
            inversedBy: book
            cascade: ["all", "merge", "persist", "refresh", "remove"]
            joinColumn:
              name: search_id
              referencedColumnName: id
              onDelete: CASCADE
              cascade: ["persist"]
    lifecycleCallbacks: {  }
