BooksSearchBundle\Entity\Book:
    type: entity
    table: null
    repositoryClass: BooksSearchBundle\Repository\BookRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
        publishedDate:
            type: datetime
            column: published_date
        description:
            type: text
            nullable: true
        pageCount:
            type: integer
            column: page_count
        categories:
            type: smallint
        language:
            type: string
            length: '3'
    lifecycleCallbacks: {  }
