BooksSearchBundle\Entity\VolumeInfo:
    type: entity
    table: null
    repositoryClass: BooksSearchBundle\Repository\VolumeInfoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        publishedDate:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        pageCount:
            type: integer
            nullable: true
        language:
            type: string
            length: 255
            nullable: true
        previewLink:
            type: string
            length: 255
        infoLink:
            type: string
            length: 255
    oneToOne:
        book:
            targetEntity: Book
            mappedBy: volumeInfo
        imageLinks:
            fetch: EAGER
            targetEntity: ImageLink
            inversedBy: volume
            cascade: ["all", "merge", "persist", "refresh", "remove"]
            joinColumn:
                name: image_id
                referencedColumnName: id          
    manyToOne:
        publisher:
            fetch: EAGER
            targetEntity: Publisher
            cascade: ["all", "merge", "persist", "refresh", "remove"]
            joinColumn:
                name: publisher_id
                referencedColumnName: id
    manyToMany:
        authors:
            fetch: EAGER
            targetEntity: Author
            cascade: ["all", "merge", "persist", "refresh", "remove"]
            joinTable:
                name: volumes_authors
                joinColumns:
                    author_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    volume_id:
                        referencedColumnName: id
        categories:
            fetch: EAGER
            targetEntity: Category
            cascade: ["all", "merge", "persist", "refresh", "remove"]
            joinTable:
                name: volumes_categories
                joinColumns:
                    category_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    volume_id:
                        referencedColumnName: id
            
    lifecycleCallbacks: {  }
