search:
    path:     /search/{page}
    defaults: 
        _controller: BooksSearchBundle:Default:search 
        page: 1
    requirements:
        page: '\d+'
        
homepage:
    path:     /{page}
    defaults: 
        _controller: BooksSearchBundle:Default:index
        page: 1
        
detail:
    path:     /book/{id}
    defaults: 
        _controller: BooksSearchBundle:Default:book
